### PR TITLE
Support ecmarkup post-processor

### PR DESCRIPTION
**Pull request by tobie**
/cc @littledan

### CODE REVIEW

**Comment by tobie** [comment]
Well, all your files have .bs extensions, so I assumed you were relying on Bikeshed and doing post-processing with Ecmarkup.

**Comment by tobie** [comment]
Is that not the case?

**Comment by littledan** [comment]
We tend to use the html extension. We don't use Bikeshed; instead, ecmarkup is a top-level tool. For example, see spec.html in [the ecma262 repo](http://github.com/tc39/ecma262/). The WebAssembly/JS API draft spec is done with Bikeshed, not ecmarkup.

**Comment by tobie** [comment]
I was just addressing the WebAssembly/JS case (which I thought, from your comment, needed an ecmarkup post-processor).

Hadn't thought about enabling this for ES. Is there an interest? Is the only build step ecmarkup?

**Comment by littledan** [comment]
WebAssembly/JS doens't use ecmarkup at all. I think we could use the pr-preview tool already if we configure the repo for it. Sorry for causing confusion earlier.

There's definite interest in TC39 in such a tool! We currently construct such diffs manually in proposal repositories, and when looking at patches, we have to read the source. Some in the committee have been waiting expectantly for years for a tool like this to drop on their doorstep, while others have feared it to be practically impossible. cc @bterlson

Separately, I think this tool could be extremely useful for WebAssembly, which represents proposals as forks of the main repository. As a beginner, I have a lot of trouble reading these proposals since I don't know where to start. cc @jfbastien @rossberg

**Comment by tobie** [comment]
> WebAssembly/JS doens't use ecmarkup at all. I think we could use the pr-preview tool already if we configure the repo for it. Sorry for causing confusion earlier.

Absolutely. Though pr-preview only handles a single source file per repo (for now). I'm not sure how many you actually have.

> There's definite interest in TC39 in such a tool! We currently construct such diffs manually in proposal repositories, and when looking at patches, we have to read the source. Some in the committee have been waiting expectantly for years for a tool like this to drop on their doorstep, while others have feared it to be practically impossible. cc @bterlson

Well, we've been using pr-preview on WebIDL pull requests for close to a year now, and rolled it out to W3C and WHATWG properties over the past year too. Mozilla just sponsored the development of a dedicated version for HTML which handles the multipage build and has been live for little over a week now (see for example: https://github.com/whatwg/html/pull/3273). A cursory look at the ES build process does imply building a custom solution for the ES spec. It shouldn't be too difficult nor take too long. I'm happy to discuss it if there's interest. Just email me.

> Separately, I think this tool could be extremely useful for WebAssembly, which represents proposals as forks of the main repository. As a beginner, I have a lot of trouble reading these proposals since I don't know where to start. cc @jfbastien @rossberg

So pr-preview is really designed for a workmode that involves sending proposals as pull requests. To make it clearer that these are proposals, we could use dedicated templates. Here again, feel free to reach out if you want to discuss a dedicated solution for your needs.

**Comment by littledan** [comment]
> Though pr-preview only handles a single source file per repo (for now). I'm not sure how many you actually have.

For TC39 proposals, there's just one relevant file. For WebAssembly, there's lots. Great to hear aout the version for multipage builds.

Personally, I don't have time to get started on this tool right now, so I'll leave this hear, but maybe one of those people who I mentioned would like to pick it up. I put this on my long-term backlog for now...

**Comment by tobie** [comment]
> Personally, I don't have time to get started on this tool right now, so I'll leave this hear, but maybe one of those people who I mentioned would like to pick it up. I put this on my long-term backlog for now...

For a compatible repo (single source file, using either Bikeshed or Specref) installation is a one-click install from the GitHub website + a small config file in the repo, e.g.: https://github.com/heycam/webidl/blob/master/.pr-preview.json.

**Comment by tobie** [comment]
> For TC39 proposals, there's just one relevant file. 

Right, but there's multiple output files (HTML, CSS, JS) which pr-preview isn't ready for.

**Comment by littledan** [comment]
> Right, but there are multiple output files (HTML, CSS, JS) which pr-preview isn't ready for.

Not these days--now it inlines the CSS and JS by default.

**Comment by tobie** [comment]
That should be trivial, then.

**Comment by littledan** [comment]
OK, I'll try to get to it sooner then!

**Comment by tobie** [comment]
I forgot how big the spec was. The HTML differ will probably not support it.

**Comment by littledan** [comment]
What's the issue?

Proposal repositories tend to be significantly smaller. It could still be useful for those.

**Comment by tobie** [comment]
The issue is the [web service](https://services.w3.org/htmldiff) we rely on for HTML diffing returns a 500 HTTP code. I haven't tested for the ES spec, maybe it's not a large as the HTML spec, but that was the issue for the latter.

**Comment by tobie** [comment]
So I tested, and the htmldiff server seems to handle the memory footprint of the ES spec. We'd need to look at how the JS and CSS files are linked and where they're uploaded, but other than that, there's no reason why we couldn't make this work just the way it works for W3C and WHATWG specs nowadays.

**Comment by tobie** [comment]
Closing this. Feel free to file an issue or reach out if you want to look into this again at some point.

**Pull request closed without merging**
