### PR TITLE
Stop relying on GitHack for HTML builds

### LINKED ISSUE #112: GitHack seems to be running over capacity
[GitHack](https://raw.githack.com) (the server that PR Preview relies on to build specs) seems to be running over capacity and is regularly returning 429 (Too Many Requests) HTTP responses.

This needs:

- Investigation to understand what the underlying issue is.
- If the underlying issue cannot be fixed, either finding and deploying alternative solutions or building a custom solution.

### PR DESCRIPTION
**Pull request by tobie**
Fixes #112

### CODE REVIEW

**Comment by tobie** [comment]
/cc @deniak 

Does that seem sound from your perspective?

**Comment by deniak** [comment]
This looks good assuming the result will be served as `text/html`.

**Comment by tobie** [comment]
If you mean when they’re served from the AWS S3 instance, then yes.

**Comment by deniak** [comment]
> If you mean when they’re served from the AWS S3 instance, then yes.

Ok, then LGTM

**Comment by deniak** [comment]
Thanks @tobie! This will help all the editors relying on pr-preview.

**Pull request merged**
