### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tobie**

### CODE REVIEW

**Comment by tripu** [comment]
@tobie, you tell me. Is the test suite enough of a guarantee? I see [the build for this PR is working](https://travis-ci.org/tobie/pr-preview/builds/468417313)&hellip;

**Comment by tobie** [comment]
No, the test suite really doesn’t cover much.

**Comment by tripu** [comment]
Then I guess this will require either improving the test suite, or testing manually&nbsp;&mdash;&nbsp;by whoever assumes maintenance of the project: you, or someone from the W3C's Systeam.

Pinging @vivienlacourba and @deniak here to get them in the loop, since I'll be leaving the team this week.

**Pull request closed without merging**
